src/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password-change"
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    url(
        r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
]

src/block/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
import profiles.urls
import accounts.urls
import local.urls
import device.urls
from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Block Site Admin"
admin.site.site_header = "Block Administration"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("users/", include(profiles.urls)),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
    # added by me
    path("local/", include(local.urls)),
    path("device/", include(device.urls)),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

src/device/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from device import views
from django.urls import path
from django.conf.urls import url

app_name = "device"
urlpatterns = [
    path('partial/<int:pk>', views.partial),
    path('', views.cripto_connect, name="connect"),
    path('<int:id>/alter', views.alter, name='alter'),
    path('global/<int:hash>', views.return_global),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/local/urls.py
from django.urls import path
from . import views
from django.urls import path
from django.conf.urls import url

app_name = "local"
urlpatterns = [
    path("", views.localmanagement, name="local"),
]

src/local/models.py
from django.db import models
from device.models import Device
from django.conf import settings


class BlockHeader(models.Model):
    hash = models.CharField(max_length=100)

class PolicyHeader(models.Model):
    GENESIS = 1
    STORE = 2
    ACCESS = 3
    MONITOR = 4
    REMOVE = 5
    ACTION_TYPES = (
        (GENESIS, 'Genesis'),
        (STORE, 'Store'),
        (ACCESS, 'Access'),
        (MONITOR, 'Monitor'),
        (REMOVE, 'Remove'),
    )
    ALLOW = 1
    DENY = 2
    ACTION = (
        (ALLOW, 'Allow'),
        (DENY, 'Deny'),
    )
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    requested_action = models.PositiveSmallIntegerField(choices=ACTION_TYPES)
    device = models.ForeignKey(Device, on_delete=models.CASCADE, blank=True, null=True)
    action = models.PositiveSmallIntegerField(choices=ACTION)

class Transactions(models.Model):
    GENESIS = 1
    STORE = 2
    ACCESS = 3
    MONITOR = 4
    REMOVE = 5
    ACTION_TYPES = (
        (GENESIS, 'Genesis'),
        (STORE, 'Store'),
        (ACCESS, 'Access'),
        (MONITOR, 'Monitor'),
        (REMOVE, 'Remove'),
    )
    prev_transaction = models.ForeignKey('self', on_delete=models.CASCADE ,blank=True, null=True)
    transaction_number = models.IntegerField()
    device = models.ForeignKey(Device, on_delete=models.CASCADE, blank=True, null=True)
    transaction_type = models.PositiveSmallIntegerField(choices=ACTION_TYPES)
    device_status = models.BooleanField(default=False)

    class Meta:
        get_latest_by = "transaction_number"

class Block(models.Model):
    prev_block = models.ForeignKey('self', on_delete=models.CASCADE ,blank=True, null=True)
    block_header = models.ForeignKey(BlockHeader, on_delete=models.CASCADE)
    policy_header = models.ManyToManyField(PolicyHeader, blank=True)
    transactions = models.ManyToManyField(Transactions, blank=True)

class BlockChain(models.Model):
    block_chain = models.ManyToManyField(Block)

src/local/views.py
from django.shortcuts import render
from device.models import Device
from django.urls import reverse
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from local.models import *


def localmanagement(request):
    if request.user.is_authenticated:

        devices = Device.objects.all()
        block = Block.objects.latest('id')
        for device in devices:
            if block.transactions.count():
                transaction = Transactions.objects.filter(device=device).latest()
                print(transaction)
                device.status = transaction.device_status
                device.save()

        context = {
            'devices': devices,
        }
        return render(request, 'local/management.html', context)
    else:
        return HttpResponseRedirect(reverse('home'))

src/local/templates/local/management.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Management{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="local" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block styles %}
<link href="{% static 'site/css/main.css' %}" rel="stylesheet">
{% endblock styles %}

{% block css %}
<style>
.center {
    text-align: center;
    background-color:black;
    color:white;
    padding:20px;
}
* {box-sizing: border-box;}
body {font-family: Arial, Helvetica, sans-serif;}
/* Float four columns side by side */
.column {
  float: left;
  width: 25%;
  padding: 0 10px;
}
/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}
/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}
</style>

{% endblock css %}

{% block container %}
<br><br><br><br><br>


<div class="container">
  <div class = "center">
      <h2>Blockchain Home Management</h2>
  </div>

  <div class="row">
    {% for d in devices %}
    <div class="column">

      <div class="card">
          {% csrf_token %}
          <h3>Fan 1</h3>
          {% if d.dh_key %}
            <a class="btn btn-warning" href="#" role="button">Activated</a>

          {% else %}
            <a class="btn btn-primary" href="{% url 'device:connect' %}" role="button">Activate Device</a>
          {% endif %}
          <br>
          <br>
          <p>Status -> {{d.status}}</p>
          <a class="btn btn-primary" href="{% url 'device:alter' id=d.id %}">Change Status</a>

      </div>
    </div>

    {% endfor %}
  </div>
</div>
{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}